#ifndef GAMECONSTANTS_H
#define GAMECONSTANTS_H

#define WINDOW_WIDTH 1280
#define WINDOW_HEIGHT 900

#define CHAR_SIZE 20

#define TILE_SIZE 10

#define DETECTION_N_FRAME 20
#define DETECTION_LIMIT 5.0

#endif // GAMECONSTANTS_H
